// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Q_MKCeZqJX586nHwKTw6qr7EM9nCrs0',
    appId: '1:855090552291:web:a4d79e2f35811e016a54d6',
    messagingSenderId: '855090552291',
    projectId: 'hypermart-ee8ef',
    authDomain: 'hypermart-ee8ef.firebaseapp.com',
    storageBucket: 'hypermart-ee8ef.firebasestorage.app',
    measurementId: 'G-7C4ZD3YFML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ELcRyWxVZwjFkoa4nmw97fGYKST-gKs',
    appId: '1:855090552291:android:9a56598fa3f5b86f6a54d6',
    messagingSenderId: '855090552291',
    projectId: 'hypermart-ee8ef',
    storageBucket: 'hypermart-ee8ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9A1lGUkWxDWEFI7wN2fE2Tqa9ZN2k570',
    appId: '1:855090552291:ios:ff20fbb88c3ff0386a54d6',
    messagingSenderId: '855090552291',
    projectId: 'hypermart-ee8ef',
    storageBucket: 'hypermart-ee8ef.firebasestorage.app',
    iosBundleId: 'com.example.hypermart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9A1lGUkWxDWEFI7wN2fE2Tqa9ZN2k570',
    appId: '1:855090552291:ios:ff20fbb88c3ff0386a54d6',
    messagingSenderId: '855090552291',
    projectId: 'hypermart-ee8ef',
    storageBucket: 'hypermart-ee8ef.firebasestorage.app',
    iosBundleId: 'com.example.hypermart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Q_MKCeZqJX586nHwKTw6qr7EM9nCrs0',
    appId: '1:855090552291:web:318cc4dbb21b26506a54d6',
    messagingSenderId: '855090552291',
    projectId: 'hypermart-ee8ef',
    authDomain: 'hypermart-ee8ef.firebaseapp.com',
    storageBucket: 'hypermart-ee8ef.firebasestorage.app',
    measurementId: 'G-NN4J51H86M',
  );
}
